# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('mpg', models.FloatField()),
                ('fuel_capacity', models.FloatField(max_length=128)),
            ],
        ),
    ]
