# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff_map', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=16)),
                ('longitude', models.CharField(max_length=16)),
                ('home', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
