# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff_map', '0003_locations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Cars',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Items',
        ),
    ]
